feat(cli): build and create a CTF containing the OCM CLI with multiple Architectures and Operating Systems (#413)
<!-- markdownlint-disable MD041 -->
#### What this PR does / why we need it

Let's try to eat our own stuff and build a component version of the OCM
CLI like OCM v1 and then push our component version to a CTF.

What was added:
- A taskfile extension that can
  - build the CLI for windows,linux,darwin(mac) in arm64,amd64
  - build a component-constructor.yaml from resource fragments
- build a ctf based on the component-constructor.yaml containing a
component version of the OCM CLI in various build formats
  - verify the ctf by downloading the resource and running the CLI again
- An extension to OCM download resource that can (just like old ocm),
use a label that hints towards a relative path under which the resource
should be stored (downloadName). This path is used in favor of the
resource name if found and no output name is defined.

What is missing compared to the OCM CLI v1 right now:
- we do not have an ocmcli-image resource yet (the docker input method
would be needed for this or we build the image separately and add it as
an access, TBD)
- while coding I noticed that I still need to pass the resource version
as part of the identity for the download, this needs to be fixed up (on
this right now, but this is part of a fix for the OCI bindings)
- We dont have component constructor templating (we maybe never will
have) and so i am using native templating via environment variables and
shell scripts

#### Which issue(s) this PR fixes
<!--
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
-->

---------

Signed-off-by: Jakob Möller <jakob.moeller@sap.com>

diff --git a/cli/Taskfile.yml b/cli/Taskfile.yml
--- a/cli/Taskfile.yml
+++ b/cli/Taskfile.yml
@@ -3,6 +3,20 @@ version: '3'
 vars:
   CLI_DOCUMENTATION_MODE: "markdown"
   CLI_DOCUMENTATION_DIRECTORY: tmp/docs
+  PROVIDER: ocm.software
+  NAME: cli
+  DEFAULT_VERSION:
+    sh: |
+      echo "0.0.0-$(date -u +%Y%m%d%H%M%S)-$(git rev-parse --short=12 HEAD)$(git diff --quiet || echo '+dirty')"
+  VERSION: '{{ .VERSION | default .DEFAULT_VERSION }}'
+  COMPONENT_CONSTRUCTOR_FILE: "{{ .TASKFILE_DIR }}/tmp/component-constructor.yaml"
+  CTF_LOCATION: '{{ .TASKFILE_DIR }}/tmp/transport-archive'
+  GOOS:
+    sh: |
+      go env GOOS
+  GOARCH:
+    sh: |
+      go env GOARCH
 tasks:
   tmp:
     cmds:
@@ -18,15 +32,128 @@ tasks:
       - go test -v -coverprofile=tmp/coverage.out ./...
     deps:
       - tmp
-  build:
-    desc: "Build the CLI"
+
+  install:
+    desc: "Install the CLI"
+    prompt: "This will install the CLI to {{ .TARGET }}, do you want to continue?"
+    interactive: true
     vars:
-        DEFAULT_VERSION:
-          sh: |
-            echo "0.0.0-$(date -u +%Y%m%d%H%M%S)-$(git rev-parse --short=12 HEAD)$(git diff --quiet || echo '+dirty')"
-        VERSION: '{{ .CLI_ARGS | default .DEFAULT_VERSION }}'
+      TARGET: /usr/local/bin
+    deps:
+      - task: build
     cmds:
-      - go build -ldflags "-X ocm.software/open-component-model/cli/cmd/version.BuildVersion={{ .VERSION }}" -o {{ .ROOT_DIR }}/tmp/bin/ocm
+      - cmd: sudo install -m 755 {{ .TASKFILE_DIR }}/tmp/bin/ocm {{ .TARGET }}
+
+  build:
+    desc: "Build the CLI in the Host Architecture"
+    deps:
+      - task: build:target
+        vars:
+          GOOS: '{{ .GOOS }}'
+          GOARCH: '{{ .GOARCH }}'
+    cmds:
+      - cmd: ln -sf {{ .TASKFILE_DIR }}/tmp/bin/ocm-{{ .GOOS }}-{{ .GOARCH }} {{ .TASKFILE_DIR }}/tmp/bin/ocm
+
+  build/multiarch:
+    desc: "Build CLI for all supported targets"
+    deps:
+      - for:
+          matrix:
+            GOOS: [ "windows", "linux", "darwin" ]
+            GOARCH: [ "amd64", "arm64" ]
+        task: build:target
+        vars:
+          GOOS: '{{.ITEM.GOOS }}'
+          GOARCH: '{{.ITEM.GOARCH }}'
+
+  build:target:
+    desc: "Build CLI for a specific GOOS/GOARCH target"
+    internal: true
+    silent: false
+    generates:
+      - tmp/bin/ocm-{{ .GOOS }}-{{ .GOARCH }}
+      - tmp/resources/ocm-{{ .GOOS }}-{{ .GOARCH }}.yaml
+    cmds:
+      - cmd: |
+          GOOS={{ .GOOS }} GOARCH={{ .GOARCH }} go build \
+            -ldflags "-X ocm.software/open-component-model/cli/cmd/version.BuildVersion={{ .VERSION }}" \
+            -o {{ .TASKFILE_DIR }}/tmp/bin/ocm-{{ .GOOS }}-{{ .GOARCH }}
+      - |
+        mkdir -p {{ .TASKFILE_DIR }}/tmp/resources
+        cat > {{ .TASKFILE_DIR }}/tmp/resources/ocm-{{ .GOOS }}-{{ .GOARCH }}.yaml <<EOF
+        - name: ocmcli
+          type: executable
+          version: {{ .VERSION }}
+          labels:
+            - name: downloadName
+              value: ocm
+          extraIdentity:
+            os: {{ .GOOS }}
+            architecture: {{ .GOARCH }}
+          relation: local
+          input:
+            type: file
+            path: {{ .TASKFILE_DIR }}/tmp/bin/ocm-{{ .GOOS }}-{{ .GOARCH }}
+        EOF
+
+  generate/ctf:
+    deps:
+      - task: generate/component-constructor
+      - task: build
+    desc: "Generate the component-constructor.yaml and build the CLI for all targets, then generate the CTF containing the Component Version"
+    cmd: |
+      rm -rf {{ .CTF_LOCATION }}
+      {{ .TASKFILE_DIR }}/tmp/bin/ocm add component-versions \
+        --constructor {{ .COMPONENT_CONSTRUCTOR_FILE }} \
+        --repository {{ .CTF_LOCATION }}
+
+  verify/ctf:
+    desc: "Verify the CTF by checking the component version and being able to fetch and run the CLI for the Host Architecture"
+    silent: true
+    deps:
+      - generate/ctf
+    vars:
+      REFERENCE: '{{ .CTF_LOCATION }}//{{ .PROVIDER }}/{{ .NAME }}'
+    dir: '{{ .TASKFILE_DIR }}/tmp/verify-ctf'
+    cmd: |
+      VERSION=$({{ .TASKFILE_DIR }}/tmp/bin/ocm get component-version {{ .REFERENCE }} -oyaml --loglevel=error | yq .component.version)
+      if [ -z "$VERSION" ]; then
+        echo "Component version not found in CTF at {{ .REFERENCE }}"
+        exit 1
+      fi
+      echo "Component version found: $VERSION"
+      
+      {{ .TASKFILE_DIR }}/tmp/bin/ocm download resource {{ .REFERENCE }}:$VERSION \
+        --identity name=ocmcli,os={{ .GOOS }},architecture={{ .GOARCH }}
+      
+      chmod +x ./ocm
+      ./ocm version
+      
+      
+
+  generate/component-constructor:
+    desc: "Generate the component-constructor.yaml by building the CLI for all targets"
+    generates:
+      - '{{ .COMPONENT_CONSTRUCTOR_FILE }}'
+    silent: true
+    deps:
+      - task: build/multiarch
+        silent: true
+    cmds:
+      - |
+        cat <<EOF > {{ .COMPONENT_CONSTRUCTOR_FILE }}
+        name: {{ .PROVIDER }}/{{ .NAME }}
+        version: {{ .VERSION }}
+        provider:
+          name: {{ .PROVIDER }}
+        resources:
+        EOF
+      - |
+        for file in {{ .TASKFILE_DIR }}/tmp/resources/*.yaml; do
+          # Indent each line by 2 spaces and append
+          cat "$file" >> {{ .COMPONENT_CONSTRUCTOR_FILE }}
+        done
+      - cat "{{ .COMPONENT_CONSTRUCTOR_FILE }}"
 
   generate/docs:
     desc: "Generate CLI Markdown documentation"
